name: recursify
description: Recursify Video Editor for recursively generated videos

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bitsdojo_window: ^0.1.1+1
  dart_vlc: ^0.1.9
  filepicker_windows: ^2.0.1
  fluent_ui: ^3.10.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  image: ^3.1.3
  process_run: ^0.12.3+2
  url_launcher: ^6.0.20
  window_manager: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono.ttf
